//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace la_tienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad_producto { get; set; }
        public int valor_producto { get; set; }
        public string foto_producto { get; set; }
        public string descripcion_prducto { get; set; }
    }
}
